"""Add nullable reserva_id and usuario_id to resena

Revision ID: b020bade6acb
Revises: 36186f70f7c9
Create Date: 2026-06-18 17:10:53.389317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b020bade6acb'
down_revision: Union[str, None] = '36186f70f7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cliente_usuario', table_name='cliente')
    op.drop_index('idx_detalle_reserva', table_name='detalle_reserva')
    op.drop_index('idx_evento_cliente', table_name='evento')
    op.drop_index('idx_pago_reserva', table_name='pago_transaccion')
    op.drop_index('idx_proveedor_usuario', table_name='proveedor')
    op.add_column('resena', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.alter_column('resena', 'reserva_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('resena', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'resena', 'usuario', ['usuario_id'], ['id'])
    op.drop_index('idx_reserva_evento', table_name='reserva')
    op.drop_index('idx_reserva_proveedor', table_name='reserva')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_reserva_proveedor', 'reserva', ['proveedor_id'], unique=False)
    op.create_index('idx_reserva_evento', 'reserva', ['evento_id'], unique=False)
    op.drop_constraint(None, 'resena', type_='foreignkey')
    op.alter_column('resena', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resena', 'reserva_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('resena', 'usuario_id')
    op.create_index('idx_proveedor_usuario', 'proveedor', ['usuario_id'], unique=False)
    op.create_index('idx_pago_reserva', 'pago_transaccion', ['reserva_id'], unique=False)
    op.create_index('idx_evento_cliente', 'evento', ['cliente_id'], unique=False)
    op.create_index('idx_detalle_reserva', 'detalle_reserva', ['reserva_id'], unique=False)
    op.create_index('idx_cliente_usuario', 'cliente', ['usuario_id'], unique=False)
    # ### end Alembic commands ###
